GET http://localhost:3000/productos
Content-Type: application/json

###
POST http://localhost:3000/productos/create
Content-Type: application/json

{
    "Marca": "Volkswagen",
    "Modelo": "Golf",
    "Pais": "Argentina"
}

###
PUT http://localhost:3000/productos/update/7
Content-Type: application/json

{
    "Marca": "Volkswagen",
    "Modelo": "Vento",
    "Pais": "Brasil"
}

###
DELETE http://localhost:3000/productos/delete/58
Content-Type: application/json

### Vendedor-----------------------------
GET http://localhost:3000/vendedor
Content-Type: application/json

###
POST http://localhost:3000/vendedor/create
Content-Type: application/json

{
    "Nombre": "Lourdes",
    "Apellido": "Acevedo"
}

###
PUT http://localhost:3000/vendedor/update/2
Content-Type: application/json

{
    "Nombre": "Matias",
    "Apellido": "Martinez"
}

###
DELETE http://localhost:3000/vendedor/delete/3
Content-Type: application/json

### Cliente-----------------------------
GET http://localhost:3000/cliente
Content-Type: application/json

###
POST http://localhost:3000/cliente/create
Content-Type: application/json

{
    "Nombre": "Ulises",
    "Apellido": "Estevez",
    "dni": 28908775
}

###
PUT http://localhost:3000/cliente/update/5
Content-Type: application/json

{
    "Nombre": "Matias",
    "Apellido": "Sosa",
    "dni": 33151445
}

###
DELETE http://localhost:3000/cliente/delete/4
Content-Type: application/json

### Ventas-----------------------------
GET http://localhost:3000/ventas
Content-Type: application/json

###
POST http://localhost:3000/ventas/create
Content-Type: application/json

{
    "fechaVenta": "2022-11-03",
    "Precio": "8500000",
    "idVendedor": 1,
    "idCliente": 5,
    "idProductos": 7
}

###
PUT http://localhost:3000/ventas/update/2
Content-Type: application/json

{
    "Nombre": "Matias",
    "Apellido": "Martinez",
    "dni": 37160789
}

###
DELETE http://localhost:3000/ventas/delete/5
Content-Type: application/json